### ISSUE TITLE
Old Pixy implementation

### ISSUE THREAD

**Issue by Diamond42474** [PseudoResonance/Pixy2JavaAPI#10]
I’m new to the Pixy and was wondering if these libraries will work with the old Pixy model, or just the Pixy 2?

**Comment by PseudoResonance** [comment]
Unfortunately, the Pixy API is totally different from the Pixy2 API in many ways, so no, this is not compatible. If you want to try, there's a porting guide [here](https://docs.pixycam.com/wiki/doku.php?id=wiki:v1:porting_guide), but it looks to me like the protocol is a bit unpolished and annoying to use. I think they made many important improvements to it for version 2, so it might be a bit difficult to get it working. Sorry I'm not able to be of much help, as I only have Pixy2s to use.

**Comment by Diamond42474** [comment]
Gotcha, thanks!
