### ISSUE TITLE
SPILink requests SPI baudrate of 2000 bits/second - that can't be right

### ISSUE THREAD

**Issue by kauailabs** [PseudoResonance/Pixy2JavaAPI#12]
It's not really clear what bitrate ends up being used on the RoboRIO when a SPI bitrate of 2000 is provided (which is what is currently written in the SPILink.java code).

I'd suggest that 2000000 is more appropriate.

**Comment by PseudoResonance** [comment]
Thank you for pointing this out, I have pushed a fixed version that properly sets the clock rate to 2,000,000Hz, or 2MHz, as defined in the Pixy2 specifications.
