### ISSUE TITLE
Outdated Wiki

### ISSUE THREAD

**Issue by mfrancis33** [PseudoResonance/Pixy2JavaAPI#13]
As of update 1.4 (February 23, 2020), the wiki is out of date. The following line of code from the wiki will generate a type-casting error:

`ArrayList<Block> blocks = pixy.getCCC().getBlocks();`

The specific error is `Type mismatch: cannot convert from int to ArrayList<Pixy2CCC.Block>`. This is because in the [1.4 update](https://github.com/PseudoResonance/Pixy2JavaAPI/commit/c49e29d1ff25e508b31b2222939d1b87a7357686), the method `getBlocks` was repurposed to retrieve the count of objects the PixyCam sees, and the old method was changed to `getBlockCache`. The wiki hasn't been updated since October 15, 2019, which is 4 months prior to the update.

**Comment by PseudoResonance** [comment]
Thank you for pointing that out, it has now been fixed!
