### ISSUE TITLE
Is there a way to get the video footage from the api to get it onto the SmartDashboard? 

### ISSUE THREAD

**Issue by Susorodni** [PseudoResonance/Pixy2JavaAPI#14]
My team just started using this API and we were having trouble interpreting it and we wanted to know.

**Comment by PseudoResonance** [comment]
No, sorry, there is no way of getting video from the Pixy2 over these interfaces. The Pixy2 can only send a video feed over USB, and there is no fully functioning Java port of the USB driver. You could take a look at these projects below if you want, but I don't think either will do the job.

What I did, is I plugged the camera into a computer, installed the Pixymon program, and set everything up on there. Once it was working properly, I connected it to the RoboRIO for the robot to use the data.

https://github.com/simra/FrcPixy2Usb
https://github.com/CodingKoopa/libpixyusb2_java
