### ISSUE TITLE
Can't Init PixyCam

### ISSUE THREAD

**Issue by SquirrelSide** [PseudoResonance/Pixy2JavaAPI#2]
I have installed the API via the Maven way (but have also tried directly copying the files, but no difference in issue either way) and I can't do pixy.init(), it just won't let me, here is a snippet of the code, and I probably did something wrong.

![image](https://user-images.githubusercontent.com/47373999/52316279-773b6280-296f-11e9-929f-aae1e8a419d8.png)

![image](https://user-images.githubusercontent.com/47373999/52316303-8e7a5000-296f-11e9-8aac-bbb402892935.png)

**Comment by SquirrelSide** [comment]
I was just being stupid, didn't put it in robotInit()


(￣▽￣*)ゞ
--

**Comment by PseudoResonance** [comment]
Oh, well glad you figured it out. :P
Please let me know if the camera works over UART/Serial. I haven't had the time to test that out, it was just in there as a start if anyone really needed it, as SPI is a much faster and more reliable option.
