### ISSUE TITLE
Resource Busy

### ISSUE THREAD

**Issue by SquirrelSide** [PseudoResonance/Pixy2JavaAPI#3]
Now this is a real issue, in he Driver Station it says I have no code and gives this: 

Warning at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:274): Robots should not quit, but yours did! 
ERROR  1  The startCompetition() method (or methods called by it) should have handled the exception above.  edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:276) 
ERROR  1  Unhandled exception: edu.wpi.first.hal.util.UncleanStatusException:  Code: -1073807246. HAL - VISA: Resource Busy  io.github.pseudoresonance.pixy2api.links.UARTLink.open(UARTLink.java:71) 
Warning at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:274): Robots should not quit, but yours did! 
ERROR  1  The startCompetition() method (or methods called by it) should have handled the exception above.  edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:276) 
ERROR  1  Unhandled exception: edu.wpi.first.hal.util.UncleanStatusException:  Code: -1073807246. HAL - VISA: Resource Busy  io.github.pseudoresonance.pixy2api.links.UARTLink.open(UARTLink.java:71) 
ERROR  1  The startCompetition() method (or methods called by it) should have handled the exception above.  edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:276) 
Warning at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:274): Robots should not quit, but yours did! 

All I did was this:
public class Robot extends IterativeRobot {
 Pixy2 _pixyCam = Pixy2.createInstance(LinkType.UART);

  @Override
  public void robotInit() {
_pixyCam.init();
}
}

[Robot.zip](https://github.com/PseudoResonance/Pixy2JavaAPI/files/2843491/Robot.zip)

Here is the code ^

**Comment by PseudoResonance** [comment]
Hello, sorry for the late reply, we are currently having some severe weather in the Seattle area.

As you're calling the regular init() function over UART, that would mean the RoboRIO is using the onboard RS-232 port. Sorry I can't test anything, I probably won't have access to a RoboRIO for the next week. But make sure you don't have anything else in your code that is already using the port.

That error should mean that something in the code is already using the port, and if not, then there must be an issue with the RoboRIO or with FIRST's implementation. I know that the serial port is not widely used, if at all, so it could be that there is some undocumented issue, as really the only thing my code is doing is here:
`new SerialPort(PIXY_UART_BAUDRATE, SerialPort.Port.kOnboard);`
I would personally recommend trying to use SPI if possible, or if not that, try I2C, but I haven't had the time to get I2C working properly either.

Sorry I'm not able to be of much help. Without being able to test anything myself, all I can really say is that using SPI is your best bet. It is a faster option anyways, so you should be able to get more data with less delay.

**Comment by sciencewhiz** [comment]
By default, the onboard RS-232 serial port is used by the serial console. You can disable this by using the imaging tool to edit the start-up settings to uncheck "enable console out"

**Comment by PseudoResonance** [comment]
@sciencewhiz Ah, that makes a lot of sense. Thank you, I had no idea the console ran on there by default!
