### ISSUE TITLE
Block class private

### ISSUE THREAD

**Issue by alexanderswerdlow** [PseudoResonance/Pixy2JavaAPI#4]
The Block class should be made public to allow users to create/modify Block objects. I'm currently seeking to create a default Block object to return in case there isn't yet a real Block from the Pixy.

**Comment by PseudoResonance** [comment]
I'm very sorry for the late response!
I don't see how it is necessary to instantiate your own Block, or other internal objects, manually as they are for the camera's output, but I did go ahead set their constructors to be public as they did have a global scope in the original C++ code in the latest update.
